CREATE TABLE SHOP(
SHOP_NO INT AUTO_INCREMENT,
SHOP_NAME VARCHAR(50),
SHOP_LOCATION VARCHAR(50),
SHOP_STATUS VARCHAR(50),
PRIMARY KEY(SHOP_NO)
);



INSERT INTO SHOP(SHOP_NO, SHOP_NAME, SHOP_LOCATION, SHOP_STATUS)
VALUES
(1, 'shop1', 'Korea', 'Y'),
(2, 'shop2', 'Korea', 'Y'),
(3, 'shop3', 'Korea', 'Y'),
(4, 'shop4', 'Japan', 'Y'),
(5, 'shop5', 'Japan', 'Y'),
(6, 'shop6', 'Japan', 'Y')

CREATE TABLE TOY(
TOY_NO INT,
TOY_NAME VARCHAR(50),
TOY_PRICE INT,
SHOP_NO INT,
PRIMARY KEY(TOY_NO)
);

INSERT INTO TOY(TOY_NO, TOY_NAME, TOY_PRICE, SHOP_NO)
			VALUE('1', 'toy1', 100, 1);

INSERT INTO TOY(TOY_NO, TOY_NAME, TOY_PRICE, SHOP_NO)
			VALUE('2', 'toy2', 200, 1);

INSERT INTO TOY(TOY_NO, TOY_NAME, TOY_PRICE, SHOP_NO)
			VALUE('3', 'toy3', 300, 2);

INSERT INTO TOY(TOY_NO, TOY_NAME, TOY_PRICE, SHOP_NO)
			VALUE('4', 'toy4', 400, 2);



CREATE TABLE SHOP_SALES(
SHOP_NO INT,
SHOP_NAME VARCHAR(50),
SHOP_LOCATION VARCHAR(100),
SHOP_STATUS VARCHAR(50),
SHOP_AMOUNT INT,
PRIMARY KEY(SHOP_NO)
);

INSERT INTO SHOP_SALES(SHOP_NO, SHOP_NAME, SHOP_LOCATION, SHOP_STATUS, SHOP_AMOUNT)
			VALUE(1, 'toy1', 'Korea', 'Y', 20000);