CREATE TABLE SHOP(
SHOP_NO INT,
SHOP_NAME VARCHAR(50),
SHOP_LOCATION VARCHAR(50),
SHOP_STATUS VARCHAR(50),
PRIMARY KEY(SHOP_NO)
);

INSERT INTO SHOP (SHOP_NO, SHOP_NAME, SHOP_LOCATION, SHOP_STATUS)
	   	    VALUE('1', 'Pizza Shop', 'Korea', 'Y');

INSERT INTO SHOP (SHOP_NO, SHOP_NAME, SHOP_LOCATION, SHOP_STATUS)
	   	    VALUE('2', 'Hamburger', 'Korea', 'Y');

INSERT INTO SHOP (SHOP_NO, SHOP_NAME, SHOP_LOCATION, SHOP_STATUS)
	   	    VALUE('3', 'InternetCafe', 'Korea', 'Y');

INSERT INTO SHOP (SHOP_NO, SHOP_NAME, SHOP_LOCATION, SHOP_STATUS)
	   	    VALUE('4', 'Cafe', 'Japan', 'N');